package screen;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;

public class EmptyStatistica {
    private JTable table1;
    private JPanel panel1;

    public static void main(String[] args) {
        JFrame frame = new JFrame("EmptyStatistica");
        frame.setContentPane(new EmptyStatistica().panel1);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }

    public EmptyStatistica() {
        justFillInDummyData();
    }

    private void justFillInDummyData() {
        //headers for the table
        DefaultTableModel model = new DefaultTableModel();
        table1.setModel(model);
        model.addColumn("Id");
        model.addColumn("First Name");
        model.addColumn("Last Name");
        model.addColumn("Company Name");
        //actual data for the table in a 2d array

        model.addRow(new Object[]{"text", "text", "text", "text"});
        model.addRow(new Object[]{"text", "text", "text", "text"});
        model.addRow(new Object[]{"text", "text", "text", "text"});
        model.addRow(new Object[]{"text", "text", "text", "text"});
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        table1 = new JTable();
        panel1.add(table1, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}
